inherit_from: rubocop-todo.yml

AllCops:
  Include:
    - bin/simulacrum
  Exclude:
    - example/*
    - example/**/*
    - bin/*
    - spec/use_simplecov.rb

TrivialAccessors:
  Exclude:
    - lib/simulacrum.rb
