browsers:
  firefox_27_osx_mavericks:
    os: OS X
    os_version: Mavericks
    browser: firefox
    browser_version: 27.0
    resolution: 1280x1024

  ie_8_windows_7:
    os: Windows
    os_version: 7
    browser: ie
    browser_version: 8.0
    resolution: 1280x1024
    requireWindowFocus: true

  iphone_5s:
    browser: iPhone
    platform: MAC
    device: iPhone 5S

  nexus_4:
    browser: android
    platform: ANDROID
    device: LG Nexus 4
